name: Budget-Book buid Pipe
on:
  push:
    tags:
      - "latest"
      - "v*"
  workflow_dispatch:

jobs: 
  Build-and-Push-Budget-book-frontend-to-docker-hub:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: budget-book/frontend
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
        with:
          ref: deployment
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            jumpdaddy/budget-book-frontend

      - name: Login to Docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

