name: Docker Image CI

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v4
        with:
          ref: deployment

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image frontend
        run: |
          cd frontend
          docker build . --file Dockerfile --tag jumpdaddy/budget-book-frontend:latest

      - name: Push to Dockerhub
        run: docker push jumpdaddy/budget-book-frontend:latest


      - name: Build the Docker image backend
        run: |
          cd backend
          docker build . --file Dockerfile --tag jumpdaddy/budget-book-backend:latest

      - name: Push to Dockerhub
        run: docker push jumpdaddy/budget-book-backend:latest