name: 'deploy to selfhosted runner on ec2'

on:
  push:
    branches:
      - deployment
  workflow_dispatch:
    
jobs:
  deployment-of-b-book-compose:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: deployment
        
      - name: go to project root and get certs from s3
        run: cd ~/actions-runner/_work/budget-book/budget-book
      - name: copy certs
        run: aws s3 cp s3://jumpbucket-dev-1612/secrets/cert.pem proxy/cert
      - name: copy key
        run: aws s3 cp s3://jumpbucket-dev-1612/secrets/privkey.pem proxy/cert
      - name: copy .env
        run: aws s3 cp s3://jumpbucket-dev-1612/secrets/.env .
      - name: login dockerhub
        run: sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: start docker-compose
        run: sudo docker-compose up --build
        
 