name: 'deploy to selfhosted runner on ec2'

on:
  push:
    branches:
      - deployment
  workflow_dispatch:
    
jobs:
  deployment-of-b-book-compose:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: deployment
        
      - name: go to project root and get certs from s3
        run: |
          cd ~/actions-runner/_work/budget-book/budget-book
          aws s3 cp s3://jumpbucket-dev-1612/secrets/cert.pem proxy/cert
          aws s3 cp s3://jumpbucket-dev-1612/secrets/privkey.pem proxy/cert
          aws s3 cp s3://jumpbucket-dev-1612/secrets/.env .

      - name: Pull Docker image frontend
        run: sudo docker pull mone19/budget-book-frontend:latest
        
      - name: Pull Docker image backend
        run: sudo docker pull mone19/budget-book-backend:latest